groups:
- name: example-alerts
  rules:
  - alert: HighErrorRate
    expr: errors_total > 5
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "High error rate in processing"
      description: "More than 5 errors have been encountered in the last minute."
